name: lovephotographic
favicon: null
layout_spectrum: 0.89657
typography_spectrum: 0.12143
title: Love Phtoographic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85ffac'
    - '#000000'
    - '#7f7f7f'
    - '#bebebe'
  brandStrength: 0.6875
  lightness: 0.625
  saturation: 0.11980921868234873
  rhythmicContrast: 0.5
purpose: []
