name: lovephotographic
favicon: null
layout_spectrum: 0.015660019125789404
typography_spectrum: 0.07606067764572799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#85ffac'
    - '#000000'
    - '#7f7f7f'
    - '#bebebe'
  brandStrength: 0.5
  lightness: 0.8799432618543506
  saturation: 0.11980921868234873
  rhythmicContrast: 0.29142109327949584
purpose: []
